# Write mode ('w')
f = open("file.txt", "w")
f.write("Hello from write mode\n")
f.close()

# Read mode ('r')
f = open("file.txt", "r")
data = f.read()
print("Read mode:", data)
f.close()

# Read and Write mode ('r+')
f = open("file.txt", "r+")
f.write("Hello from r+ mode\n")
f.seek(0)
data = f.read()
print("Read and Write mode:", data)
f.close()

# Write and Read mode ('w+')
f = open("file.txt", "w+")
f.write("Hello from w+ mode\n")
f.seek(0)
data = f.read()
print("Write and Read mode:", data)
f.close()

# Append mode ('a')
f = open("file.txt", "a")
f.write("Hello from append mode\n")
f.close()

# Append and Read mode ('a+')
f = open("file.txt", "a+")
f.write("Hello from append and read mode\n")
f.seek(0)
data = f.read()
print("Append and Read mode:", data)
f.close()
